(define (double f) (lambda (x) (f (f x))))
(define (inc x) (+ 1 x))
(display ((double inc) 1))
(newline)
(display (((double (double double)) inc) 5))
(newline)
(define (compose f g) (lambda (x) (f (g x))))
(define (square x) (* x x))
(display ((compose square inc) 6))
(newline)
(define (repeated f k)
  (if (= k 1)
      f
      (repeated (compose f f) (- k 1))))
(display ((repeated square 2) 5))
(newline)
