(define (make-account balance account-password)
  (define (withdraw amount)
    (if (>= balance amount)
	(begin (set! balance (- balance amount)) balance)
	"Insufficient funds!"))
  (define (deposit amount)
    (set! balance (+ amount balance))
    balance)
  (define error-calls 0)
  (define (dispatch password m)
    (if (eq? password account-password)
	(begin (set! error-calls 0)
	  (cond ((eq? m 'withdraw) withdraw)
		((eq? m 'deposit) deposit)
		(else (error "Unknown mode!"))))
	(lambda (x) (begin
		      (set! error-calls (+ 1 error-calls))
		      (if (>= error-calls 7) (display "Call the cops!\n"))
		      "Access denied!"))))
  dispatch)

(define acc (make-account 100 'secret))
(display ((acc 'secret 'withdraw) 30))
(newline)
(display ((acc 'secret 'deposit) 100))
(newline)
(display ((acc 'secret2 'withdraw) 100))
(newline)
(display ((acc 'secret2 'withdraw) 100))
(newline)
(display ((acc 'secret2 'withdraw) 100))
(newline)
(display ((acc 'secret2 'withdraw) 100))
(newline)
(display ((acc 'secret2 'withdraw) 100))
(newline)
(display ((acc 'secret2 'withdraw) 100))
(newline)
(display ((acc 'secret2 'withdraw) 100))
(newline)
(display ((acc 'secret2 'withdraw) 100))
(newline)

